[platformio]
boards_dir = boards
src_dir = src
include_dir = include
default_envs = genesis_mini_m0_serial

[env:genesis_mini_m0_serial]
platform = espressif32
board = axiometa_genesis_mini
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM20
monitor_port = COM20
build_flags =
  -DBAIT_AND_BEAT_M0_SERIAL=1

[env:genesis_mini_pin_probe]
platform = espressif32
board = axiometa_genesis_mini
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = COM20
monitor_port = COM20
build_flags =
  -DBAIT_AND_BEAT_PIN_PROBE=1
